### ISSUE TITLE
Incompatible with Physics mod

### ISSUE THREAD

**Issue by DonFlymoor** [MoriyaShiine/enchancement#15]
### Mod version

1.18-13

### A description of the issue

When the physics mod is enabled, odd rectangles flash when the game is loading and it start loading from the beginning, repeating forever.

### Log or crash report

[20:32:14] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks java.util.concurrent.CompletionException: java.lang.IllegalStateException: Redundant texture list for particle botania:wisp 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?] 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] Caused by: java.lang.IllegalStateException: Redundant texture list for particle botania:wisp 	at net.minecraft.client.particle.ParticleManager.loadTextureList(ParticleManager:276) ~[?:?] 	at net.minecraft.client.particle.ParticleManager.method_18837(ParticleManager:227) ~[?:?] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] 	... 6 more [20:32:14] [Worker-Main-10/WARN]: Unable to load model: 'minecraft:note_block#instrument=harp,note=0,powered=true' referenced from: minecraft:note_block#instrument=harp,note=0,powered=true: java.lang.IllegalStateException: zip file closed [20:32:14] [Worker-Main-4/WARN]: Unable to load model: 'minecraft:light_gray_wall_banner#facing=north' referenced from: minecraft:light_gray_wall_banner#facing=north: java.lang.IllegalStateException: zip file closed [20:32:14] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/infested_cracked_stone_bricks.json' missing model for variant: 'minecraft:infested_cracked_stone_bricks#' [20:32:14] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/infested_cracked_stone_bricks.json': java.lang.IllegalStateException: zip file closed

**Comment by MoriyaShiine** [comment]
Are you sure this mod causes it? I don't see enchancement anywhere in that log. Also please try on 1.18.2
