### ISSUE TITLE
components breaking projectiles when projectilesBypassCooldownTimer is false

### ISSUE THREAD

**Issue by jitterdev** [MoriyaShiine/enchancement#150]
### Mod version

1.20-9

### A description of the issue

![image](https://github.com/MoriyaShiine/enchancement/assets/64605731/83309504-0442-4ac4-a85e-16664a556172)
![Medal_mzQsvgBEvR](https://github.com/MoriyaShiine/enchancement/assets/64605731/d650910c-18e1-436c-8ab5-f56cd651a7f4)
```
java.util.NoSuchElementException: class_1685['entity.minecraft.trident'/23658, l='ServerLevel[world]', x=-4.65, y=159.92, z=3.46] provides no component of type enchancement:delay
        at dev.onyxstudios.cca.api.v3.component.ComponentKey.get(ComponentKey.java:92) ~[cardinal-components-base-5.2.2-9148ba1f751e9e24.jar:?]
        at net.minecraft.class_1309.localvar$cog000$enchancement$projectilesBypassCooldownTimer(class_1309.java:25198) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5643(class_1309.java:1126) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.method_5643(class_1308.java:10167) ~[server-intermediary.jar:?]
        at net.minecraft.class_1685.method_7454(class_1685.java:138) ~[server-intermediary.jar:?]
        at net.minecraft.class_1676.method_7488(class_1676.java:153) ~[server-intermediary.jar:?]
        at net.minecraft.class_1665.method_5773(class_1665.java:227) ~[server-intermediary.jar:?]
        at net.minecraft.class_1685.method_5773(class_1685.java:90) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.mixinextras$bridge$accept$215(class_1937.java) ~[server-intermediary.jar:?]
        at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:115) ~[neruina-1.3.0-fabric+1.18.2-1.20.1.jar:?]
        at net.minecraft.class_1937.wrapOperation$fgc000$neruina$catchTickingEntities(class_1937.java:16548) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[server-intermediary.jar:?]
        at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bip000$carpet$modifiedRunLoop(MinecraftServer.java:19442) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[04:03:34] [Server thread/WARN]: Neruina Caught Exception
java.util.NoSuchElementException: class_1685['entity.minecraft.trident'/23682, l='ServerLevel[world]', x=-4.74, y=159.83, z=2.68] provides no component of type enchancement:delay
        at dev.onyxstudios.cca.api.v3.component.ComponentKey.get(ComponentKey.java:92) ~[cardinal-components-base-5.2.2-9148ba1f751e9e24.jar:?]
        at net.minecraft.class_1309.localvar$cog000$enchancement$projectilesBypassCooldownTimer(class_1309.java:25198) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5643(class_1309.java:1126) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.method_5643(class_1308.java:10167) ~[server-intermediary.jar:?]
        at net.minecraft.class_1685.method_7454(class_1685.java:138) ~[server-intermediary.jar:?]
        at net.minecraft.class_1676.method_7488(class_1676.java:153) ~[server-intermediary.jar:?]
        at net.minecraft.class_1665.method_5773(class_1665.java:227) ~[server-intermediary.jar:?]
        at net.minecraft.class_1685.method_5773(class_1685.java:90) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.mixinextras$bridge$accept$215(class_1937.java) ~[server-intermediary.jar:?]
        at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:115) ~[neruina-1.3.0-fabric+1.18.2-1.20.1.jar:?]
        at net.minecraft.class_1937.wrapOperation$fgc000$neruina$catchTickingEntities(class_1937.java:16548) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[server-intermediary.jar:?]
        at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bip000$carpet$modifiedRunLoop(MinecraftServer.java:19442) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]```
        

### Log or crash report

_No response_

**Comment by MoriyaShiine** [comment]
whoops lol
