### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by r4trick** [MoriyaShiine/enchancement#68]
### Mod version

enchancement-1.19-7.jar

### A description of the issue

the mode wont work on my minecraft server for some odd reason
![2022-11-19_19 06 28](https://user-images.githubusercontent.com/118640568/202876449-20da307b-7284-4278-8c91-a70d0c94f8fb.png)

**Comment by MoriyaShiine** [comment]
Do the client and server have the same config file? What mods do you have installed? Can you attach a log?

**Comment by r4trick** [comment]
> t

![image](https://user-images.githubusercontent.com/118640568/202876751-0a7ecb81-31e1-4adf-897b-32584102e05d.png)
A potential solution has been determined:
         - Install fabric, version 0.48.0 or later.
         - Install fabric-api, version 0.64.0 or later.
         - Replace mod 'Fabric Loader' (fabricloader) 0.14.9 with version 0.14.10 or later.
Unmet dependency listing:
         - Mod 'Bookshelf' (bookshelf) 16.1.11 requires any version of fabric, which is missing!
         - Mod 'Enchancement' (enchancement) 1.19-7 requires version 0.14.10 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.9!
         - Mod 'Enchancement' (enchancement) 1.19-7 requires version 0.64.0 or later of fabric-api, which is missing!
         - Mod 'Impaled' (impaled) 1.1.4 requires version 0.48.0 or later of fabric, which is missing!
         - Mod 'Step Height Entity Attribute' (step-height-entity-attribute) 1.0.0 requires any version of fabric, which is missing!
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]

**Comment by MoriyaShiine** [comment]
That log doesn't correspond to the original issue, but you need to install fabric loader 0.14.10, and use the 1.19.2 version of fabric api (you have a 1.19.3 version)

Make sure both client and server have the same set of mods and config changes

**Comment by r4trick** [comment]
I have fabric 1.19.2 and just got the right fabric api and now this is whats showing up



A potential solution has been determined:
         - Replace mod 'Enchancement' (enchancement) 1.19-7 with any version that is compatible with:
                 - fabricloader 0.14.9
                 - fabric-api 0.63.0+1.19.2
Unmet dependency listing:
         - Mod 'Enchancement' (enchancement) 1.19-7 requires version 0.14.10 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.9!
         - Mod 'Enchancement' (enchancement) 1.19-7 requires version 0.64.0 or later of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.63.0+1.19.2!
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]


![image](https://user-images.githubusercontent.com/118640568/202876964-403db399-a747-47a5-bbf5-5d61c84f4361.png)
